# Site settings
title: Lens
description: Just another fine responsive site template by <a href="http://html5up.net">HTML5 UP</a>
baseurl: "0904AshleyPerez.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url: https://www.facebook.com/ashley.perez.7923
github_url: https://github.com/0904AshleyPerez
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/ashleyy_pc9/?hl=es-la
linkedin_url: 
pinterest_url: https://www.pinterest.com.mx/ashleyjazive/_saved/
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
